POST http://localhost:3000/api/user/create-or-update-revenue-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiYWRtaW4tZGV2ZWxvcG1lbnRAZ21haWwuY29tIn0sImlhdCI6MTcyNzcxNzM5Nn0.mIQvFSD1FrAOIVAKqWJIaoZ0P0hmuVSn73OsfiLm9Hw

{
    "userId": "cm1varsjy0000w259c3mrin0c",
    "month": "JANUARY",
    "dailyGoal": "10000"
}


###

POST http://localhost:3000/api/user/create-or-update-revenue-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiY20xcDRkN2U1MDAwMHE1dWhpc203enAwMiIsImVtYWlsIjoiYXJ0aHVyQGV4YW1wbGUuY29tIiwibmFtZSI6IkFydGh1ciBTaWx2YSJ9LCJpYXQiOjE3Mjc3MTE0Njh9.YryC69av0GN3PXrB3DttfdW23FzNZqlybdmdNx5-l2U

{
    "userId": "cm1sc29qa000010pugvmoqka4",
    "month": "JANUARY",
    "monthlyGoal": "2"
}


###
POST http://localhost:3000/api/user/create-or-update-revenue-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiY20xcDRkN2U1MDAwMHE1dWhpc203enAwMiIsImVtYWlsIjoiYXJ0aHVyQGV4YW1wbGUuY29tIiwibmFtZSI6IkFydGh1ciBTaWx2YSJ9LCJpYXQiOjE3Mjc3MTE0Njh9.YryC69av0GN3PXrB3DttfdW23FzNZqlybdmdNx5-l2U
    
{
    "userId": "cm1sc29qa000010pugvmoqka4",
    "month": "JANUARY",
    "action": "Lançar uma nova campanha de marketing para aumentar as vendas"
}


###

POST http://localhost:3000/api/user/create-or-update-revenue-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiY20xcDRkN2U1MDAwMHE1dWhpc203enAwMiIsImVtYWlsIjoiYXJ0aHVyQGV4YW1wbGUuY29tIiwibmFtZSI6IkFydGh1ciBTaWx2YSJ9LCJpYXQiOjE3Mjc3MTE0Njh9.YryC69av0GN3PXrB3DttfdW23FzNZqlybdmdNx5-l2U
    
{
    "userId": "cm1sc29qa000010pugvmoqka4",
    "month": "JANUARY",
    "action": "Lançar uma nova campanha"
}


###

POST http://localhost:3000/api/user/create-or-update-revenue-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiY20xcDRkN2U1MDAwMHE1dWhpc203enAwMiIsImVtYWlsIjoiYXJ0aHVyQGV4YW1wbGUuY29tIiwibmFtZSI6IkFydGh1ciBTaWx2YSJ9LCJpYXQiOjE3Mjc3MTE0Njh9.YryC69av0GN3PXrB3DttfdW23FzNZqlybdmdNx5-l2U
    
{
    "userId": "cm1sc29qa000010pugvmoqka4",
    "month": "JANUARY",
    "action": "Lançar uma nova campanha de marketing"
}