POST http://localhost:3000/api/admin/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiYWRtaW4tZGV2ZWxvcG1lbnRAZ21haWwuY29tIn0sImlhdCI6MTcyNzcxNzM5Nn0.mIQvFSD1FrAOIVAKqWJIaoZ0P0hmuVSn73OsfiLm9Hw

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "purchaseDate": "2024-01-01",
    "expirationDate": "2025-01-01"
}