GET http://localhost:3000/api/user/get-daily-tasks/cm1p4d7e50000q5uhism7zp02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiY20xcDRkN2U1MDAwMHE1dWhpc203enAwMiIsImVtYWlsIjoiYXJ0aHVyQGV4YW1wbGUuY29tIiwibmFtZSI6IkFydGh1ciBTaWx2YSJ9LCJpYXQiOjE3Mjc3MTE0Njh9.YryC69av0GN3PXrB3DttfdW23FzNZqlybdmdNx5-l2U