PUT http://localhost:3000/api/admin/update-user/cm1p977my0000ewh7aj8oclmf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiYWRtaW4tZGV2ZWxvcG1lbnRAZ21haWwuY29tIn0sImlhdCI6MTcyNzcxNzM5Nn0.mIQvFSD1FrAOIVAKqWJIaoZ0P0hmuVSn73OsfiLm9Hw

{
    "name": "Arthur Kroger"
}